# Launch instances, runs some tasks
# and then terminate them
---
- hosts: localhost
  connection: local
  tasks:
    - name: Terminate Instances
      ec2_instance_facts:
        region: us-east-2
      register: ec2_info
 
    - name: displaying output
      debug: msg="{{item.instance_id}}"
      with_items: "{{ec2_info.instances}}"
 
    - name: terminate
      ec2:
        instance_ids: "{{ec2_info.instances}}"
        region: us-east-2
        state: absent
        wait: yes
      with_items: "{{ec2_info.instances}}"
